title: Great Great Jekyll Theme
description: "Jekyll theme for Double Great projects."
url: "https://doublegreat.dev"
baseurl: /great-great-jekyll-theme

author:
  name: "@double-great"

github: double-great/great-great-jekyll-theme

permalink: /:title/

header_pages:
  - documentation.md
  - index.html
  - post.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github
